### ISSUE TITLE
Tabs on /user page don't work well on mobile

### ISSUE THREAD

**Issue by minorOffense** [coldfrontlabs/drupalcamp_zen#2]
Visit the sign in or register pages when not logged in on a phone. Doesn't look good.

**Comment by tiffanytse** [comment]
Created buttons out of tabs instead; Commit fa113c1368e2053431bd0fd18db430119404de0b

**Comment by tiffanytse** [comment]
commit 8611ec3f0c3dc2fcb6f52b2c3e4cff746f9a6c86
